name: Check CRLF
on: push
jobs:
  check-crlf:
    name: Check CRLF action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v3
      - name: Use action to check for CRLF endings
        uses: erclu/check-crlf@v1